plannerID: 1

trajInit:
  vLift: 0.08
  hLift: 0.15
  trajTime: 3 # Only affect init trajectory

misc:
  enableOptimizer: true
  useCfgSpace: false
  enableOptVis: true
  enableBenchmark: false
  # Benchmark result save path
  benchmarkSavePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/data/optBenchmark2.csv
  robotProfilePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/data/robotProfile2.csv

RRTPlanner:
  maxTime: 1.3
  collBallRadius: 0.02
  excludeRadius: 0.06 # TODO: use exclude cylinder radius?
  collMargin: 0.04


