trajInit:
  vLift: 0.08
  hLift: 0.15
  trajTime: 3 # Only affect init trajectory

plannerID: 1

misc:
  enableOptVis: true

RRTPlanner:
  maxTime: 0.3
  collBallRadius: 0.03
  excludeRadius: 0.08 # TODO: use exclude cylinder radius?
  collMargin: 0.04

