# sim: false # Loaded in launch file
mu: 0.4
mass: 45.0
# inertia_diag: [1.0, 2.0, 2.4]
inertia_diag: [0.7, 1.4, 1.8]
# inertia_diag: [0.3, 0.6, 0.9]
gravity: 9.81
loop_rate: 200.0
Kp: 36.0
Kd: 18.0 # kd = 2 \zeta \sqrt(kp)
pidgrf_Kp: 25.0 # When this equals loop_rate, pid acts as pass-through 
pidgrf_lim: 60000.0
# pidgrf_T: 0.005
# pidgrf_tau: 0.0025
exp_pose_topic_name: /exp_odom
fdb_pose_topic_name: /base_odom # Hardware
# fdb_pose_topic_name_sim: /torso_odom # gazebo (original data)
fdb_pose_topic_name_sim: /base_odom # gazebo (sim sensor)
exp_foot_state_topic_name: /exp_foot_state
fdb_foot_state_topic_name: /hexapod/foot_state_fdb
footcmd_topic_name: /hexapod/hlc/foot_cmd_track
body_frame: base
world_frame: odom
joint_kp_st: [0.02, 0.02, 0.02]
# joint_kp_st: [0.005, 0.005, 0.005]
joint_kd_st: [0.4, 0.4, 0.4]
joint_kp_sw: [0.02, 0.02, 0.02]
joint_kd_sw: [0.4, 0.4, 0.4]
# joint_kp: [0.04, 0.04, 0.04]
# joint_kd: [1.0, 1.0, 1.0]
# joint_kp_sim_st: [60.0, 60.0, 60.0]


