plannerID: 0

trajInit:
  # perpendicular to the ground (avoid collision detection)
  vLift: 0.2 # For trajopt
  # vLift: 0.018 # For raibert planner init traj
  vLiftNormalRandomize: 2.0 # Rand normal for RE-PLANNING (orthogonal disk randomization)
  hLift: 0.1
  trajTime: 2

misc:
  enableOptimizer: true
  reOptimize: true
  useCfgSpace: true # Do not change this (this file is for cfg space)
  useCfgCommand: true
  enableVis: true
  enableOptVis: false # Visualize the optimization process
  optVisRate: 10
  enableBenchmark: true
  # Benchmark result save path
  # benchmarkSavePath: /home/user/HexLabCodeSpace/planner_ws/src/legged_traj_planner/legged_traj_plan_examples/data/benchmark/optBenchmark.csv
  # robotProfilePath: /home/user/HexLabCodeSpace/planner_ws/src/legged_traj_planner/legged_traj_plan_examples/data/benchmark/robotProfile.csv
  benchmarkSavePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/data/optBenchmark2.csv
  robotProfilePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/data/robotProfile2.csv

LFTPlanner:
  searcher:
    useLeggedBorderCheck: true
  optimizer:
    lengthPerPiece: 0.35 # FIXME: pieces > 3, the vLift effect is not obvious, when pieces = 3 it will lead to strange outcome
    allocSpeed: 0.2 # NOTE: crucial for optimization
    relCostTol: 1.0e-4
    smoothingFactor: 6.0e-2 # IMPORTANT: smooth obstacle is good for optimization
    integralResolution: 8
    enableSpaceDeform: false
    spaceDeform1: 1.0
    spaceDeform2: 1.0
    spaceDeform3: 1.0
  penalty:
    energyWeight: 1.0
    timeWeight: 2 # PROBLEM: too large or too small will leads to max-try error
    joint1PosMin: -0.785
    joint1PosMax: 0.785
    joint2PosMin: -0.5233
    joint2PosMax: 3.14
    joint3PosMin: -0.6978
    joint3PosMax: 3.925
    jointMaxVel: 100.0
    jointMaxAcc: 500.0
    jointPosWeight: 0.4
    jointVelWeight: 0.1
    jointAccWeight: 0.1
    CollBall1Rad: 0.06
    CollBall2Rad: 0.055
    CollBall3Rad: 0.04
    CollBall1Weight: 0.0
    CollBall2Weight: 4.0
    CollBall3Weight: 4.0
    FootCollExcludeBallRad: 0.05
    FootCollExcludeBallSmoothRad: 0.05
    primitivePos1: 0.0
    primitivePos2: 0.0
    primitivePos3: 0.0
    primitiveWeight1: 0.0
    primitiveWeight2: 0.0
    primitiveWeight3: 0.0
