plannerID: 2

trajInit:
  vLift: 0.08
  vLiftNormalRandomize: 0.5
  hLift: 0.15
  trajTime: 3 # Only affect init trajectory

misc:
  enableOptimizer: true
  reOptimize: true
  reOptimizeMaxTry: 10
  useCfgSpace: true
  useCfgCommand: true
  enableVis: true
  enableOptVis: true
  optVisRate: 10
  enableBenchmark: true
  # Benchmark result save path
  OptBenchmarkSavePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/data/optBenchmark2.csv
  robotProfilePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/data/robotProfile2.csv

RRTCfgPlanner:
  maxTime: 0.1
  CollBall2Rad: 0.05
  CollBall3Rad: 0.03
  excludeRadius: 0.05 # exclude sphere radius
  collMargin: 0.00  # collision margin in the middle of the traj
  rrtMaxStepSize: 0.6
  joint1PosMin: -0.785
  joint1PosMax: 0.785
  joint2PosMin: -0.349
  joint2PosMax: 3.14
  joint3PosMin: -0.6978
  joint3PosMax: 3.403
  checker:
    enableReachableCheckRetry: True
    maxReachableCheckRetry: 20


