plannerID: 5

trajInit:
  vLift: 0.014 # For trajopt
  vLiftNormalRandomize: 1.5 # Rand normal for RE-PLANNING (orthogonal disk randomization)
  hLift: 0.1
  trajTime: 2

misc:
  enableOptimizer: true
  reOptimize: false
  reOptimizeMaxTry: 100
  useCfgSpace: true # Do not change this (this file is for cfg space)
  useCfgCommand: true
  enableVis: true
  enableOptVis: false # Visualize the optimization process
  optVisRate: 10
  enableBenchmark: true
  # Benchmark result save path
  # OptBenchmarkSavePath: /home/user/HexLabCodeSpace/planner_ws/src/legged_traj_planner/legged_traj_plan_examples/data/benchmark/optBenchmark.csv
  # robotProfilePath: /home/user/HexLabCodeSpace/planner_ws/src/legged_traj_planner/legged_traj_plan_examples/data/benchmark/robotProfile.csv
  OptBenchmarkSavePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/data/optBenchmark2.csv
  robotProfilePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/data/robotProfile2.csv

StompCfgPlanner:
  searcher:
    enablePolyPathSearch: false
    guideSurfType: 2 # 0: ground, 1: keypoints, 2: convolution
    guideSurfConvKernelSize: 10
    guideSurfConvKernelInterval: 0.03
    collBallCheckRad2: 0.05
    collBallCheckRad3: 0.03
  checker:
    enableReachableCheckRetry: False
    maxReachableCheckRetry: 1
  optimizer:
    stompNumTimesteps: 20 # i.e. Traj resolution
    stompStdDev1: 0.4     # Noise StdDev for stochastic rollouts
    stompStdDev2: 1.4
    stompStdDev3: 1.0
    stompNumIters: 100    # Iterations for optimization
    stompNumItersAfterValid: 0
    stompNumRollouts: 10  # Rollouts for one iteration
    stompMaxRollouts: 100
    stompCtrlCostWeight: 0.3
    stompExpCostSensitivity: 6.0
  penalty:
    smoothingFactor: 1.0e-2
    joint1PosMin: -0.785
    joint1PosMax: 0.785
    joint2PosMin: -0.349
    joint2PosMax: 3.14
    joint3PosMin: -0.6978
    joint3PosMax: 3.403
    jointPosWeight: 0.4
    CollBall1Rad: 0.06
    CollBall2Rad: 0.05
    CollBall3Rad: 0.03
    CollBall1Weight: 0.0
    CollBall2Weight: 20.0
    CollBall3Weight: 20.0
    FootCollExcludeBallRad: 0.04
    FootCollExcludeBallSmoothRad: 0.01
