plannerID: 4

trajInit:
  # perpendicular to the ground (avoid collision detection)
  vLift: 0.014 # For trajopt
  # vLift: 0.018 # For raibert planner init traj
  vLiftNormalRandomize: 1.5 # Rand normal for RE-PLANNING (orthogonal disk randomization)
  trajRandomizeScale: 0.0
  hLift: 0.1
  trajTime: 2

misc:
  enableOptimizer: true
  reOptimize: false
  reOptimizeMaxTry: 100
  useCfgSpace: false # Do not change this (this file is for cfg space)
  useCfgCommand: true
  enableVis: true
  enableOptVis: false # Visualize the optimization process
  optVisRate: 6
  enableBenchmark: true
  # Benchmark result save path
  # OptBenchmarkSavePath: /home/user/HexLabCodeSpace/planner_ws/src/legged_traj_planner/legged_traj_plan_examples/data/benchmark/optBenchmark.csv
  # robotProfilePath: /home/user/HexLabCodeSpace/planner_ws/src/legged_traj_planner/legged_traj_plan_examples/data/benchmark/robotProfile.csv
  OptBenchmarkSavePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/data/optBenchmark2.csv
  robotProfilePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/data/robotProfile2.csv

StompPlanner:
  optimizer:
    stompNumTimesteps: 20
    stompStdDev1: 0.1
    stompStdDev2: 0.3
    stompStdDev3: 0.5
    stompNumIters: 60
    stompNumItersAfterValid: 0
    stompNumRollouts: 60
    stompMaxRollouts: 60
    stompCtrlCostWeight: 1.0
    stompExpCostSensitivity: 1.0
  penalty:
    smoothingFactor: 1.0e-2
    CollBall3Rad: 0.04
    CollBall3Weight: 20.0
    FootCollExcludeBallRad: 0.06
    # FootCollExcludeBallSmoothRad: 0.02
