plannerID: 5

trajInit:
  vLift: 0.014 # For trajopt
  vLiftNormalRandomize: 1.5 # Rand normal for RE-PLANNING (orthogonal disk randomization)
  hLift: 0.1
  trajTime: 2

misc:
  enableOptimizer: true
  reOptimize: false
  reOptimizeMaxTry: 100
  useCfgSpace: true # Do not change this (this file is for cfg space)
  useCfgCommand: true
  enableVis: true
  enableOptVis: false # Visualize the optimization process
  optVisRate: 10
  enableBenchmark: true
  # Benchmark result save path
  # benchmarkSavePath: /home/user/HexLabCodeSpace/planner_ws/src/legged_traj_planner/legged_traj_plan_examples/data/benchmark/optBenchmark.csv
  # robotProfilePath: /home/user/HexLabCodeSpace/planner_ws/src/legged_traj_planner/legged_traj_plan_examples/data/benchmark/robotProfile.csv
  benchmarkSavePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/data/optBenchmark2.csv
  robotProfilePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/data/robotProfile2.csv

StompCfgPlanner:
  optimizer:
    stompNumTimesteps: 20
    stompStdDev1: 0.4
    stompStdDev2: 1.4
    stompStdDev3: 1.0
    stompNumIters: 100
    stompNumItersAfterValid: 0
    stompNumRollouts: 10
    stompMaxRollouts: 100
    stompCtrlCostWeight: 0.3
    stompExpCostSensitivity: 6.0
  penalty:
    smoothingFactor: 1.0e-2
    joint1PosMin: -0.785
    joint1PosMax: 0.785
    joint2PosMin: -0.5233
    joint2PosMax: 3.14
    joint3PosMin: -0.6978
    joint3PosMax: 3.925
    jointPosWeight: 0.4
    CollBall1Rad: 0.06
    CollBall2Rad: 0.06
    CollBall3Rad: 0.03
    CollBall1Weight: 0.0
    CollBall2Weight: 20.0
    CollBall3Weight: 20.0
    FootCollExcludeBallRad: 0.06
    FootCollExcludeBallSmoothRad: 0.01
