
# NOTE: Planner benchmark settings override 
misc:
  useCfgCommand: true
  reOptimize: true
  reOptimizeMaxTry: 100
  enableVis: true
  enableOptVis: false
  optVisRate: 300
  enableBenchmark: false
  OptBenchmarkSavePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/temp/OptBenchmark.csv
  ReachableBenchmarkSavePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/temp/ReachableBenchmark.csv
  robotProfilePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/temp/RobotProfileRecord.csv


RaibertPlanner:
  rosRate: 100

  # Enable Reachability Check (if envableVis is True, output will be visualized) 
  enableReachableCheck: true
  reachableCheckSize: 30 # (size*size, in 0.75*0.75 area)

  OptBenchmarkSavePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/temp/RaibertPlannerBenchmark.yaml
