
# NOTE: Planner benchmark settings override 
misc:
  useCfgCommand: true
  reOptimize: true
  reOptimizeMaxTry: 100
  enableVis: true
  enableOptVis: false
  optVisRate: 300
  enableBenchmark: false
  OptBenchmarkSavePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/temp/OptBenchmark.csv
  ReachableBenchmarkSavePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/temp/ReachableBenchmark.csv
  robotProfilePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/temp/RobotProfileRecord.csv


RaibertPlanner:
  rosRate: 100
  OptBenchmarkSavePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/temp/RaibertPlannerBenchmark.yaml