
# NOTE: Planner benchmark settings override 
misc:
  useCfgCommand: true
  reOptimize: true
  reOptimizeMaxTry: 1000
  enableVis: true
  enableOptVis: true
  optVisRate: 6
#   enableBenchmark: true
#   benchmarkSavePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/temp/SwingTrajPlannerBenchmark.csv
#   robotProfilePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/temp/RobotProfileRecord.csv


StateSequencePlanner:
  rosRate: 100
  cmdMctsSearchNodeNum: 100
  navMctsSearchNodeNum: 600
  cmdExtrapolatePointNum: 50
  cmdExtrapolateDeltaT: 0.01
  navExtrapolateSamplesNum: 100

  swingTrajPreOpt: false
  shutdownAfterPreOpt: false
  execOnKeyboardCmd: false
  # Demo select
  # demoPath: # NOTE: offered by launch file
  savePlannedStates: false
  # Executing saved states on startup
  execSavedStates: true 

  # Benchmark
  benchmarkSavePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/temp/StateSequencePlannerBenchmark.yaml