
# NOTE: Planner benchmark settings override 
misc:
  reOptimize: false
  reOptimizeMaxTry: 3
  enableVis: false
  enableOptVis: false
  enableBenchmark: true
  OptBenchmarkSavePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/temp/SwingTrajPlannerBenchmark.csv
  ReachableBenchmarkSavePath: null
  robotProfilePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/temp/RobotProfileRecord.csv


StateSequencePlanner:
  rosRate: 100
  stepTime: 2
  cmdMctsSearchNodeNum: 300
  navMctsSearchNodeNum: 600
  cmdExtrapolatePointNum: 50
  cmdExtrapolateDeltaT: 0.01
  navExtrapolateSamplesNum: 100

  swingTrajPreOpt: true
  shutdownAfterPreOpt: true
  execOnKeyboardCmd: false
  # Demo select
  # demoPath: # NOTE: offered by launch file
  savePlannedStates: false
  # Executing saved states on startup
  execSavedStates: true 

  # Benchmark
  OptBenchmarkSavePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/temp/StateSequencePlannerBenchmark.yaml