StateSequencePlanner:
  rosRate: 100
  cmdMctsSearchNodeNum: 100
  navMctsSearchNodeNum: 600
  cmdExtrapolatePointNum: 50
  cmdExtrapolateDeltaT: 0.01
  navExtrapolateSamplesNum: 100
  # Demo select
  # demoPath: # NOTE: offered by launch file
  savePlannedStates: true
  # Executing saved states on startup
  execSavedStates: true