GridMapInterface:
  topicName: /grid_map
  groundLayerName: elevation_inpainted
  topicNameCeiling: /grid_map
  ceilingLayerName: ceiling
  sdfMargin: 0.2
  normalTangentCrtic: 1.0
  enableHeightFilter: false
  maxHeight: 0.1
  minHeight: -100.0