GridMapInterface:
  topicName: /grid_map
  groundLayerName: elevation_inpainted
  topicNameCeiling: /grid_map
  ceilingLayerName: ceiling
  sdfMargin: 0.2
  normalTangentCrtic: 1.0
  enableHeightFilter: false
  maxHeight: 0.1
  minHeight: -100.0
  sdfEnable: true
  travErodeRad: 0.0
  centerBoxAlwaysTrav: false
  centerBoxWidth: 1.6
  centerBoxLen: 1.6
  # Foothold map parameters
  footholdNormalTangentCrtic: 0.8
  footholdEnableHeightFilter: false
  footholdMaxHeight: 0.1
  footholdMinHeight: -100.0
  footholdErodeRad: 0.05
  footholdCenterBoxAlwaysTrav: false
  footholdCenterBoxWidth: 0.8
  footholdCenterBoxLen: 0.8
