# kp: [0, 0, 0]
# kp: [30, 30, 30]
# kp: [100, 100, 100]
kp: [500, 500, 500]
# kd: [0.1, 0.1, 0.1]
kd: [5, 5, 5]

y_shift: 0.25
z_shift: -0.28

interval: 2 #sec
swing_amp: [0.05, 0.05, 0.0] #meter
swing_phase: [0, 1.57, 0] # rad


# force: [0.0, 0.0, -60]
force: [0.0, 0.0, 0]